name: Python Powered
description: Blogging about Python
meta_description: "Python, APIs, data, AI"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
# domain_name: 'https://jasonrhaas.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
# github.url: https://jasonrhaas.github.io/kasper

# Details for the RSS feed generator
url:            'http://jasonrhaas.com'
author:         'Jason Haas'
